spring:
  application:
    name: cj_alimtalk_service
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # resources 아래 application-secret.yml 로드 (없으면 무시)
  config:
    import: optional:classpath:application-secret.yml